# Generated by Django 2.1 on 2018-11-22 22:55

import chargify.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chargify_id', models.IntegerField(null=True, unique=True)),
                ('name', models.CharField(max_length=75)),
                ('kind', models.CharField(choices=[('metered_component', 'Metered Component'), ('quantity_based_component', 'Quantity Based Component'), ('on_off_component', 'On/Off Component')], default='metered_component', max_length=30)),
                ('pricing_scheme', models.CharField(choices=[('per_unit', 'Per-Unit'), ('volume', 'Volume'), ('tiered', 'Tiered'), ('stairstep', 'Stairstep')], max_length=10, null=True)),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('unit_name', models.CharField(max_length=75)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            bases=(models.Model, chargify.models.ChargifyBaseModel),
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('masked_card_number', models.CharField(max_length=25, null=True)),
                ('expiration_month', models.IntegerField(blank=True, null=True)),
                ('expiration_year', models.IntegerField(blank=True, null=True)),
                ('credit_type', models.CharField(choices=[('Visa', 'Visa'), ('MasterCard', 'MasterCard')], max_length=25, null=True)),
                ('billing_address', models.CharField(default='', max_length=75, null=True)),
                ('billing_city', models.CharField(default='', max_length=75, null=True)),
                ('billing_state', models.CharField(default='', max_length=2, null=True)),
                ('billing_zip', models.CharField(default='', max_length=15, null=True)),
                ('billing_country', models.CharField(blank=True, default='United States', max_length=75, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            bases=(models.Model, chargify.models.ChargifyBaseModel),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chargify_id', models.IntegerField(null=True, unique=True)),
                ('_first_name', models.CharField(max_length=50, null=True)),
                ('_last_name', models.CharField(max_length=50, null=True)),
                ('_email', models.EmailField(max_length=254, null=True)),
                ('_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('organization', models.CharField(blank=True, max_length=75, null=True)),
                ('active', models.BooleanField(default=True)),
                ('chargify_created_at', models.DateTimeField(null=True)),
                ('chargify_updated_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, chargify.models.ChargifyBaseModel),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chargify_id', models.IntegerField(null=True, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('name', models.CharField(max_length=75)),
                ('handle', models.CharField(default='', max_length=75)),
                ('accounting_code', models.CharField(max_length=30, null=True)),
                ('interval_unit', models.CharField(choices=[('month', 'Month'), ('day', 'Day')], default='month', max_length=10)),
                ('interval', models.IntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
            ],
            bases=(models.Model, chargify.models.ChargifyBaseModel),
        ),
        migrations.CreateModel(
            name='ProductFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chargify_id', models.IntegerField(null=True, unique=True)),
                ('accounting_code', models.CharField(max_length=30, null=True)),
                ('name', models.CharField(max_length=75)),
                ('description', models.TextField(default='')),
                ('handle', models.CharField(default='', max_length=75)),
            ],
            bases=(models.Model, chargify.models.ChargifyBaseModel),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chargify_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('state', models.CharField(blank=True, choices=[('trialing', 'Trialing'), ('assessing', 'Assessing'), ('active', 'Active'), ('soft_failure', 'Soft Failure'), ('past_due', 'Past Due'), ('suspended', 'Suspended'), ('canceled', 'Cancelled'), ('expired', 'Expired')], default='', max_length=15, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('current_period_started_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_ends_at', models.DateTimeField(blank=True, null=True)),
                ('trial_started_at', models.DateTimeField(blank=True, null=True)),
                ('trial_ended_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('next_assessment_at', models.DateTimeField(blank=True, null=True)),
                ('next_billing_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('last_deactivation_at', models.DateTimeField(blank=True, null=True)),
                ('last_activation_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('credit_card', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='chargify.CreditCard')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chargify.Customer')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chargify.Product')),
            ],
            bases=(models.Model, chargify.models.ChargifyBaseModel),
        ),
        migrations.CreateModel(
            name='SubscriptionComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('allocated_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('enabled', models.BooleanField(default=False)),
                ('component', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chargify.Component')),
                ('subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chargify.Subscription')),
            ],
            bases=(models.Model, chargify.models.ChargifyBaseModel),
        ),
        migrations.AddField(
            model_name='product',
            name='product_family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chargify.ProductFamily'),
        ),
        migrations.AddField(
            model_name='component',
            name='product_family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chargify.ProductFamily'),
        ),
    ]
